### ISSUE TITLE
Logo Design for keybon.io

### ISSUE THREAD

**Issue by zuurw** [eduardorasgado/keybon.io#1]
Hi @eduardorasgado, do you want a logo for this project? I would love to create something for it.

Do you have any special request for this logo? Do you have any Idea?

Best Regards!

Zuur

**Comment by eduardorasgado** [comment]
Hi @zuurw, if you want to create a logo for this project you are free to do it, this is a game, it is inspired on a computer keyboard, it is a minimalistic game.  Best regards bro.

**Comment by zuurw** [comment]
Hi @eduardorasgado  Here are my design for this game, see if you like it.

![proposta keiborn](https://user-images.githubusercontent.com/40801473/45415714-1f295a00-b676-11e8-8254-648a7ccac9f3.png)

White version looks really good on the website :)

![site k](https://user-images.githubusercontent.com/40801473/45415759-323c2a00-b676-11e8-82cd-064fa2a3dd3a.png)

If you want I can make the letter K more thin.

Best Regards!

Zuur Willem!

**Comment by eduardorasgado** [comment]
I like it bro! The white version could be to the left of the name of the game. Great work, send me the PR @zuurw :100:

**Comment by zuurw** [comment]
Sorry for the delay in answering, but I had some personal problems to solve and I did not have much time to focus on the projects in github. But now I'm back.
So I will submit PR today!!

**Comment by eduardorasgado** [comment]
Well done bro, just keep going :muscle:
